services:
  api:
    build: .
    depends_on:
      - postgres
    volumes:
      - api_data:/app/logs
  postgres:
    image: postgres:16
    container_name: restaurant_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
  api_data: